### ISSUE TITLE
bot launcher ikke, se descr.

### ISSUE THREAD

**Issue by JakobDanielsen** [JakobDanielsen/discordbot#36]
<img width="1035" alt="Skjermbilde 2022-01-06 kl  09 24 40" src="https://user-images.githubusercontent.com/91836235/148352423-ee2085d4-0032-4b98-8730-ffed6611fe99.png">

Bot launcher ikke fra min pc

**Comment by heleneamlo** [comment]
prøv npm uninstall @discordjs
så npm install @discordjs

**Comment by heleneamlo** [comment]
problem was fixed with a nodejs update
